print('This is my first program')
print('I have to learn it everyday')
print('I must finish the book in less than a month')
print('Then move on to the front-end development')
print('I want to do machine Learning')